angular.module('app')

.factory('UnicodeSrv', function(){
  var all = [
    // stars
    {char: '★', html: '&#9733;', unicode: 'U+2605', tags: ['étoile noire', 'black star', 'star']},
    {char: '☆', html: '&#9734;', unicode: 'U+2606', tags: ['étoile blanche', 'white star', 'star']},
    {char: '✪', html: '&#10026;', unicode: 'U+272A', tags: ['étoile blanche cerclée', 'circled white star', 'star']},
    {char: '✫', html: '&#10027;', unicode: 'U+272B', tags: ['molette noire', 'open centre black star', 'star']},
    {char: '✯', html: '&#10031;', unicode: 'U+272F', tags: ['étoile rayonnante', 'pinwheel star', 'star']},
    {char: '✰', html: '&#10032;', unicode: 'U+2730', tags: []},
    {char: '✮', html: '&#10030;', unicode: 'U+272E', tags: []},
    {char: '✭', html: '&#10029;', unicode: 'U+272D', tags: []},
    {char: '✩', html: '&#10025;', unicode: 'U+2729', tags: []},
    {char: '⚝', html: '&#9885;', unicode: 'U+269D', tags: ['étoile blanche ajourée', 'outlined white star', 'star']},
    {char: '✦', html: '&#10022;', unicode: 'U+2726', tags: ['étoile noire à quatre branches', 'black four pointed star', 'star']},
    {char: '✧', html: '&#10023;', unicode: 'U+2727', tags: ['étoile blanche à quatre branches', 'white four pointed star', 'star']},
    {char: '✨', html: '&#10024;', unicode: 'U+2728', tags: []},
    {char: '✸', html: '&#10040;', unicode: 'U+2738', tags: ['grosse étoile rectiligne à huit branches', 'heavy eight pointed rectilinear black star', 'star']},
    {char: '✵', html: '&#10037;', unicode: 'U+2735', tags: ['étoile rayonnante à huit branches', 'eight pointed pinwheel star', 'star']},
    {char: '✷', html: '&#10039;', unicode: 'U+2737', tags: ['étoile rectiligne à huit branches', 'eight pointed rectilinear black star', 'star']},
    {char: '✴', html: '&#10036;', unicode: 'U+2734', tags: ['étoile noire à huit branches', 'eight pointed black star', 'star']},
    {char: '✹', html: '&#10041;', unicode: 'U+2739', tags: ['étoile noire à douze branches', 'awelve pointed black star', 'star', 'badge', 'certificate']},
    // asterisks
    {char: '⁕', html: '&#8277;', unicode: 'U+2055', tags: ['point-fleur', 'flower punctuation mark', 'star']},
    {char: '✲', html: '&#10034;', unicode: 'U+2732', tags: ['astérisque percé', 'open centre asterisk', 'star']},
    {char: '✱', html: '&#10033;', unicode: 'U+2731', tags: ['gros astérisque', 'heavy asterisk', 'star']},
    {char: '❉', html: '&#10057;', unicode: 'U+2749', tags: ['astérisque pommeté', 'balloon-spoked asterisk', 'star']},
    {char: '❋', html: '&#10059;', unicode: 'U+274B', tags: ['gros astérisque-hélice à huit branches larmées', 'heavy eight teardrop-spoked propeller asterisk', 'star']},
    {char: '✺', html: '&#10042;', unicode: 'U+273A', tags: ['astérisque à seize branches', 'sixteen pointed asterisk', 'star']},
    {char: '✳', html: '&#10035;', unicode: 'U+2733', tags: ['astérisque à huit branches', 'eight spoked asterisk', 'star']},
    {char: '⚹', html: '&#9913;', unicode: 'U+26B9', tags: ['sextile', 'star']},
    {char: '∗', html: '&#8727;', unicode: 'U+2217', tags: ['opérateur astérisque', 'asterisk operator', 'star']},
    {char: '⁎', html: '&#8270;', unicode: 'U+204E', tags: ['astérisque baissé', 'low asterisk', 'star']},
    {char: '⁑', html: '&#8273;', unicode: 'U+2051', tags: ['deux astérisques alignés verticalement', 'two asterisks aligned vertically', 'star']},
    {char: '⁂', html: '&#8258;', unicode: 'U+2042', tags: ['astérisme', 'asterism', 'star']},
    // snowflake
    {char: '❅', html: '&#10053;', unicode: 'U+2745', tags: ['flocon de neige à trois folioles transpercé', 'tight trifoliate snowflake']},
    {char: '❄', html: '&#10052;', unicode: 'U+2744', tags: ['flocon de neige', 'snowflake']},
    {char: '❆', html: '&#10054;', unicode: 'U+2746', tags: ['gros flocon de neige à chevrons', 'heavy chevron snowflake']},
    // bars
    {char: '‐', html: '&#8208;', unicode: 'U+2010', tags: ['trait d\'union', 'hyphen', 'ponctuation', 'bar', 'black']},
    {char: '–', html: '&#8211;', unicode: 'U+2013', tags: ['tiret demi-cadratin', 'en dash', 'ponctuation', 'bar', 'black']},
    {char: '‒', html: '&#8210;', unicode: 'U+2012', tags: ['tiret numérique', 'figure dash', 'ponctuation', 'bar', 'black']},
    {char: '—', html: '&#8212;', unicode: 'U+2014', tags: ['tiret cadratin', 'em dash', 'ponctuation', 'bar', 'black']},
    {char: '−', html: '&#8722;', unicode: 'U+2212', tags: ['signe moins', 'minus sign', 'ponctuation', 'bar', 'black']},
    {char: '―', html: '&#8213;', unicode: 'U+2015', tags: ['barre horizontale', 'horizontal bar', 'ponctuation', 'bar', 'black']},
    {char: '⁃', html: '&#8259;', unicode: 'U+2043', tags: ['puce trait d\'union', 'hyphen bullet', 'black', 'bar']},
    // dots
    {char: '‧', html: '&#8231;', unicode: 'U+2027', tags: ['point de coupure de mot', 'hyphenation point', 'black', 'circle']},
    {char: '․', html: '&#8228;', unicode: 'U+2024', tags: ['point de conduite simple', 'one dot leader', 'ponctuation', 'black', 'circle', 'one horizontal dot']},
    {char: '᎐', html: '&#5008;', unicode: 'U+1390', tags: ['signe de ton éthiopien yezät', 'ethiopic tonal mark yizet', 'ponctuation', 'black', 'circle', 'one vertical dot']},
    {char: '‥', html: '&#8229;', unicode: 'U+2025', tags: ['point de conduite double', 'two dot leader', 'ponctuation', 'black', 'circle', 'two horizontal dots']},
    {char: '∶', html: '&#8758;', unicode: 'U+2236', tags: ['rapport', 'ratio', 'ponctuation', 'black', 'circle', 'two vertical dots']},
    {char: '᎓', html: '&#5011;', unicode: 'U+1393', tags: ['signe de ton éthiopien bref rekrek', 'ethiopic tonal mark short rikrik', 'ponctuation', 'black', 'circle', 'two vertical dots']},
    {char: '⁚', html: '&#8282;', unicode: 'U+205A', tags: ['deux-points en capitale', 'two dot punctuation', 'ponctuation', 'black', 'circle', 'two vertical dots']},
    {char: '…', html: '&#8230;', unicode: 'U+2026', tags: ['points de suspension', 'horizontal ellipsis', 'ponctuation', 'black', 'square', 'three horizontal squares']},
    {char: '⋯', html: '&#8943;', unicode: 'U+22EF', tags: ['trois points médians', 'midline horizontal ellipsis', 'three dots back']},
    {char: '᎒', html: '&#5010;', unicode: 'U+1392', tags: ['signe de ton éthiopien rekrek', 'ethiopic tonal mark rikrik', 'ponctuation', 'black', 'circle', 'three vertical dots']},
    {char: '᎒', html: '&#8285;', unicode: 'U+205D', tags: ['trois-points vertical', 'tricolon', 'ponctuation', 'black', 'circle', 'three vertical dots']},
    {char: '⋮', html: '&#8942;', unicode: 'U+22EE', tags: ['trois points suspendus', 'vertical ellipsis', 'three dots back']},
    {char: '⋰', html: '&#8944;', unicode: 'U+22F0', tags: ['trois points diagonaux vers le coin haut à droite', 'up right diagonal ellipsis', 'three dots back']},
    {char: '⋱', html: '&#8945;', unicode: 'U+22F1', tags: ['trois points diagonaux vers le coin bas à droite', 'down right diagonal ellipsis', 'three dots back']},
    {char: '⁞', html: '&#8286;', unicode: 'U+205E', tags: ['quatre-points vertical', 'vertical four dots', 'ponctuation', 'black', 'circle', 'four vertical dots']},
    {char: '⦙', html: '&#10649;', unicode: 'U+2999', tags: []},
    {char: '⁖', html: '&#8278;', unicode: 'U+2056', tags: ['trois-points', 'three dot punctuation', 'dots', 'black']},
    {char: '∴', html: '&#8756;', unicode: 'U+2234', tags: ['par conséquent', 'therefore', 'three dots', 'black']},
    {char: '∵', html: '&#8757;', unicode: 'U+2235', tags: ['parce que', 'because', 'three dots', 'black']},
    {char: '∷', html: '&#8759;', unicode: 'U+2237', tags: ['proportion', 'proportion', 'four dots', 'black']},
    {char: '⁘', html: '&#8280;', unicode: 'U+2058', tags: ['quatre-points en losange', 'four dot punctuation', 'dots', 'black']},
    {char: '⁛', html: '&#8283;', unicode: 'U+205B', tags: ['quatre-points en croix', 'four dot mark', 'dots', 'black']},
    {char: '⁙', html: '&#8281;', unicode: 'U+2059', tags: ['cinq-points en quinconce', 'five dot punctuation', 'dots', 'black']},
    {char: '፨', html: '&#4968;', unicode: 'U+1368', tags: ['séparateur de paragraphes éthiopien', 'ethiopic paragraph separator', 'dots', 'black']},
    // circles
    {char: '⬤', html: '&#11044;', unicode: 'U+2B24', tags: []},
    {char: '◯', html: '&#9711;', unicode: 'U+25EF', tags: ['grand cercle', 'large circle']},
    {char: '●', html: '&#9679;', unicode: 'U+25CF', tags: ['disque noir', 'black circle', 'black dot']},
    {char: '○', html: '&#9675;', unicode: 'U+25CB', tags: ['cercle blanc', 'white circle', 'white dot']},
    {char: '◉', html: '&#9673;', unicode: 'U+25C9', tags: ['cercle blanc évidé', 'fisheye', 'circled black dot']},
    {char: '◎', html: '&#9678;', unicode: 'U+25CE', tags: ['deux cercles concentriques', 'bullseye', 'circled white dot']},
    {char: '◌', html: '&#9676;', unicode: 'U+25CC', tags: ['cercle en pointillés', 'cotted circle']},
    {char: '◐', html: '&#9680;', unicode: 'U+25D0', tags: ['cercle avec moitié gauche noire', 'circle with left half black']},
    {char: '◑', html: '&#9681;', unicode: 'U+25D1', tags: ['cercle avec moitié droite noire', 'circle with right half black']},
    {char: '◒', html: '&#9682;', unicode: 'U+25D2', tags: ['cercle avec moitié inférieure noire', 'circle with lower half black']},
    {char: '◓', html: '&#9683;', unicode: 'U+25D3', tags: ['cercle avec moitié supérieure noire', 'circle with upper half black']},
    {char: '◔', html: '&#9684;', unicode: 'U+25D4', tags: ['cercle avec quadrant supérieur droit noir', 'circle with upper right quadrant black']},
    {char: '◕', html: '&#9685', unicode: 'U+25D5', tags: ['cercle avec quadrant supérieur gauche blanc', 'circle with all but upper left quadrant black']},
    {char: '◴', html: '&#9716;', unicode: 'U+25F4', tags: ['cercle blanc à quartier supérieur gauche', 'white circle with upper left quadrant']},
    {char: '◵', html: '&#9717;', unicode: 'U+25F5', tags: []},
    {char: '◶', html: '&#9718;', unicode: 'U+25F6', tags: []},
    {char: '◷', html: '&#9719;', unicode: 'U+25F7', tags: []},
    {char: '◍', html: '&#9677;', unicode: 'U+25CD', tags: ['cercle hachuré verticalement', 'circle with vertical fill']},
    {char: '◖', html: '&#9686;', unicode: 'U+25D6', tags: ['demi-disque gauche noir', 'left calf clack circle']},
    {char: '◗', html: '&#9687;', unicode: 'U+25D7', tags: ['demi-disque droite noir', 'right calf clack circle']},
    {char: '⚫', html: '&#9899;', unicode: 'U+26AB', tags: ['cercle moyen noir', 'medium black circle', 'black', 'circle']},
    {char: '⚪', html: '&#9898;', unicode: 'U+26AA', tags: []},
    {char: '⦁', html: '&#10625;', unicode: 'U+2981', tags: []},
    {char: '•', html: '&#8226;', unicode: 'U+2022', tags: ['puce', 'bullet', 'black', 'circle']},
    {char: '·', html: '&#183;', unicode: 'U+00B7', tags: ['point médian', 'middle dot', 'ponctuation', 'black', 'circle']},
    {char: '◦', html: '&#9702;', unicode: 'U+25E6', tags: ['petit cercle blanc', 'white bullet']},
    {char: '⚬', html: '&#9900;', unicode: 'U+26AC', tags: []},
    {char: '°', html: '&#176;', unicode: 'U+00B0', tags: ['symbole degré', 'degree sign', 'ponctuation', 'circle', 'white']},
    // arrows
    {char: '←', html: '&#8592;', unicode: 'U+2190', tags: ['flèche vers la gauche', 'leftwards arrow', 'arrow']},
    {char: '↑', html: '&#8593;', unicode: 'U+2191', tags: ['flèche vers le haut', 'upwards arrow', 'arrow']},
    {char: '→', html: '&#8594;', unicode: 'U+2192', tags: ['flèche vers la droite', 'rightwards arrow', 'arrow']},
    {char: '↓', html: '&#8595;', unicode: 'U+2193', tags: ['flèche vers le bas', 'downwards arrow', 'arrow']},
    {char: '↖', html: '&#8598;', unicode: 'U+2196', tags: ['flèche nord-ouest', 'north west arrow', 'arrow']},
    {char: '↗', html: '&#8599;', unicode: 'U+2197', tags: ['flèche nord-est', 'north east arrow', 'arrow']},
    {char: '↘', html: '&#8600;', unicode: 'U+2198', tags: ['flèche sud-est', 'south east arrow', 'arrow']},
    {char: '↙', html: '&#8601;', unicode: 'U+2199', tags: ['flèche sud-ouest', 'south west arrow', 'arrow']},
    {char: '↩', html: '&#8617;', unicode: 'U+21A9', tags: ['flèche vers la gauche avec crochet', 'leftwards arrow with hook', 'arrow', 'back']},
    {char: '↪', html: '&#8618;', unicode: 'U+21AA', tags: ['flèche vers la droite avec crochet', 'rightwards arrow with hook', 'arrow', 'forward']},
    {char: '↶', html: '&#8630;', unicode: 'U+21B6', tags: ['flèche semi-circulaire en sens positif en chef', 'anticlockwise top semicircle arrow', 'arrow', 'back']},
    {char: '↷', html: '&#8631;', unicode: 'U+21B7', tags: ['flèche semi-circulaire en sens négatif en chef', 'clockwise top semicircle arrow', 'arrow', 'forward']},
    {char: '↺', html: '&#8634;', unicode: 'U+21BA', tags: ['flèche en sens positif à cercle ouvert', 'anticlockwise open circle arrow', 'arrow', 'refresh']},
    {char: '↻', html: '&#8635;', unicode: 'U+21BB', tags: ['flèche en sens négatif à cercle ouvert', 'clockwise open circle arrow', 'arrow']},
    {char: '⟲', html: '&#10226;', unicode: 'U+27F2', tags: []},
    {char: '⟳', html: '&#10227;', unicode: 'U+27F3', tags: []},
    {char: '↔', html: '&#8596;', unicode: 'U+2194', tags: ['flèche bilatérale', 'left right arrow', 'arrow']},
    {char: '↕', html: '&#8597;', unicode: 'U+2195', tags: ['flèche haut et bas', 'up down arrow', 'arrow']},
    {char: '⇄', html: '&#8644;', unicode: 'U+21C4', tags: ['flèche vers la droite par-dessus flèche vers la gauche', 'rightwards arrow over leftwards arrow', 'arrow', 'exchange']},
    {char: '⇆', html: '&#8646;', unicode: 'U+21C6', tags: ['flèche vers la gauche par-dessus flèche vers la droite', 'leftwards arrow over rightwards arrow', 'arrow', 'exchange']},
    {char: '⇅', html: '&#8645;', unicode: 'U+21C5', tags: ['flèche vers le haut à gauche d\'une flèche vers le bas', 'upwards arrow leftwards of downwards arrow', 'arrow']},
    {char: '⇵', html: '&#8693;', unicode: 'U+21F5', tags: ['flèche vers le bas à gauche d\'une flèche vers le haut', 'leftwards arrow upwards of downwards arrow', 'arrow']},
    {char: '⇇', html: '&#8647;', unicode: 'U+21C7', tags: ['paire de flèches vers la gauche', 'leftwards paired arrows', 'arrow']},
    {char: '⇈', html: '&#8648;', unicode: 'U+21C8', tags: ['paire de flèches vers le haut', 'upwards paired arrows', 'arrow']},
    {char: '⇉', html: '&#8649;', unicode: 'U+21C9', tags: ['paire de flèches vers la droite', 'rightwards paired arrows', 'arrow']},
    {char: '⇊', html: '&#8650;', unicode: 'U+21CA', tags: ['paire de flèches vers le bas', 'downwards paired arrows', 'arrow']},
    {char: '⇶', html: '&#8694;', unicode: 'U+21F6', tags: ['trois flèches vers la droite', 'three rightwards arrows', 'arrow']},
    {char: '↚', html: '&#8602;', unicode: 'U+219A', tags: ['flèche vers la gauche barrée', 'leftwards arrow with stroke', 'arrow']},
    {char: '↛', html: '&#8603;', unicode: 'U+219B', tags: ['flèche vers la droite barrée', 'rightwards arrow with stroke', 'arrow']},
    {char: '⇷', html: '&#8695;', unicode: 'U+21F7', tags: ['flèche vers la gauche barrée verticalement', 'leftwards arrow with vertical stroke', 'arrow']},
    {char: '⇸', html: '&#8696;', unicode: 'U+21F8', tags: ['flèche vers la droite barrée verticalement', 'rightwards arrow with vertical stroke', 'arrow']},
    {char: '⇺', html: '&#8698;', unicode: 'U+21FA', tags: ['flèche vers la gauche barrée deux fois verticalement', 'leftwards arrow with double vertical stroke', 'arrow']},
    {char: '⇻', html: '&#8699;', unicode: 'U+21FB', tags: ['flèche vers la droite barrée deux fois verticalement', 'rightwards arrow with double vertical stroke', 'arrow']},
    {char: '↜', html: '&#8604;', unicode: 'U+219C', tags: ['flèche vers la gauche ondulée', 'leftwards wave arrow', 'arrow']},
    {char: '↝', html: '&#8605;', unicode: 'U+219D', tags: ['flèche vers la droite ondulée', 'rightwards wave arrow', 'arrow']},
    {char: '↞', html: '&#8606;', unicode: 'U+219E', tags: ['flèche vers la gauche à deux pointes', 'leftwards two headed arrow', 'arrow']},
    {char: '↟', html: '&#8607;', unicode: 'U+219F', tags: ['flèche vers la haut à deux pointes', 'upwards two headed arrow', 'arrow']},
    {char: '↠', html: '&#8608;', unicode: 'U+21A0', tags: ['flèche vers la droite à deux pointes', 'rightwards two headed arrow', 'arrow']},
    {char: '↡', html: '&#8609;', unicode: 'U+21A1', tags: ['flèche vers la bas à deux pointes', 'downwards two headed arrow', 'arrow']},
    {char: '➔', html: '&#10132;', unicode: 'U+2794', tags: []},
    {char: '➙', html: '&#10137;', unicode: 'U+2799', tags: []},
    {char: '➜', html: '&#10140;', unicode: 'U+279C', tags: []},
    {char: '➝', html: '&#10141;', unicode: 'U+279D', tags: []},
    {char: '➞', html: '&#10142;', unicode: 'U+279E', tags: []},
    {char: '➟', html: '&#10143;', unicode: 'U+279F', tags: []},
    {char: '➡', html: '&#10145;', unicode: 'U+27A1', tags: []},
    {char: '➤', html: '&#10148;', unicode: 'U+27A4', tags: []},
    {char: '➩', html: '&#10153;', unicode: 'U+27A9', tags: []},
    {char: '➪', html: '&#10154;', unicode: 'U+27AA', tags: []},
    // circled / uncircled
    {char: '⊕', html: '&#8853;', unicode: 'U+2295', tags: ['plus cerclé', 'circled plus', 'circled']},
    {char: '⊖', html: '&#8854;', unicode: 'U+2296', tags: ['moins cerclé', 'circled minus', 'circled']},
    {char: '⊗', html: '&#8855;', unicode: 'U+2297', tags: ['multiplié par cerclé', 'circled times', 'circled']},
    {char: '⊘', html: '&#8856;', unicode: 'U+2298', tags: ['barre oblique de division cerclé', 'circled division slash', 'circled']},
    {char: '⊙', html: '&#8857;', unicode: 'U+2299', tags: ['opérateur point cerclé', 'circled dot operator', 'circled']},
    {char: '⋅', html: '&#8901;', unicode: 'U+22C5', tags: ['opérateur point', 'dot operator']},
    {char: '⊚', html: '&#8858;', unicode: 'U+229A', tags: ['opérateur rond cerclé', 'circled ring operator', 'circled']},
    {char: '∙', html: '&#8729;', unicode: 'U+2219', tags: ['opérateur puce', 'bullet operator', 'black', 'circle']},
    {char: '∘', html: '&#8728;', unicode: 'U+2218', tags: ['opérateur rond', 'ring operator', 'circle', 'white']},
    {char: '⊛', html: '&#8859;', unicode: 'U+229B', tags: ['opérateur astérisque cerclé', 'circled asterisk operator', 'circled']},
    {char: '⊜', html: '&#8860;', unicode: 'U+229C', tags: ['égal cerclé', 'circled equals', 'circled']},
    {char: '⊝', html: '&#8861;', unicode: 'U+229D', tags: ['tiret cerclé', 'circled dash', 'circled']},
    {char: '⋆', html: '&#8902;', unicode: 'U+22C6', tags: ['opérateur étoile', 'star operator']},
    // checks
    {char: '☐', html: '&#9744;', unicode: 'U+2610', tags: []},
    {char: '☑', html: '&#9745;', unicode: 'U+2611', tags: []},
    {char: '☒', html: '&#9746;', unicode: 'U+2612', tags: []},
    {char: '✅', html: '&#9989;', unicode: 'U+2705', tags: []},
    {char: '✔', html: '&#10004;', unicode: 'U+2714', tags: []},
    {char: '✓', html: '&#10003;', unicode: 'U+2713', tags: []},
    {char: '✘', html: '&#10008;', unicode: 'U+2718', tags: []},
    {char: '✗', html: '&#10007;', unicode: 'U+2717', tags: []},
    {char: '✖', html: '&#10006;', unicode: 'U+2716', tags: []},
    {char: '✕', html: '&#10005;', unicode: 'U+2715', tags: []},
    {char: '❌', html: '&#10060;', unicode: 'U+274C', tags: []},
    {char: '❎', html: '&#10062;', unicode: 'U+274E', tags: []},
    // hands
    {char: '☚', html: '&#9754;', unicode: 'U+261A', tags: []},
    {char: '☛', html: '&#9755;', unicode: 'U+261B', tags: []},
    {char: '☜', html: '&#9756;', unicode: 'U+261C', tags: []},
    {char: '☝', html: '&#9757;', unicode: 'U+261D', tags: []},
    {char: '☞', html: '&#9758;', unicode: 'U+261E', tags: []},
    {char: '☟', html: '&#9759;', unicode: 'U+261F', tags: []},
    {char: '✊', html: '&#9994;', unicode: 'U+270A', tags: []},
    {char: '✋', html: '&#9995;', unicode: 'U+270B', tags: []},
    {char: '✌', html: '&#9996;', unicode: 'U+270C', tags: []},
    {char: '✍', html: '&#9997;', unicode: 'U+270D', tags: []},
    // others
    {char: '☉', html: '&#9737;', unicode: 'U+2609', tags: []},
    {char: '⌾', html: '&#9022;', unicode: 'U+233E', tags: ['symbole de fonction apl beigne', 'apl functional symbol circle jot', 'circled', 'dot', 'white']},
    {char: '⍟', html: '&#9055;', unicode: 'U+235F', tags: ['symbole de fonction apl citron', 'apl functional symbol circle star', 'circled', 'star', 'dark']},
    {char: '©', html: '&#169;', unicode: 'U+00A9', tags: ['symbole copyright', 'copyright sign', 'brand']},
    {char: '®', html: '&#174;', unicode: 'U+00AE', tags: ['symbole marque déposée', 'registered sign', 'brand']},
    {char: '☃', html: '&#9731;', unicode: 'U+2603', tags: ['bonhomme de neige', 'snowman']},
    {char: '¢', html: '&#162;', unicode: 'U+00A2', tags: ['symbole centime', 'cent sign', 'money']},
    {char: '£', html: '&#163;', unicode: 'U+00A3', tags: ['symbole livre', 'pound sign', 'money']},
    {char: '¥', html: '&#165;', unicode: 'U+00A5', tags: ['symbole yen', 'yen sign', 'money']},
    {char: '‣', html: '&#8227;', unicode: 'U+2023', tags: ['puce triangulaire', 'triangular bullet', 'black', 'triangle', 'play']},
    {char: '∎', html: '&#8718;', unicode: 'U+220E', tags: ['ce qu\'il fallait démontrer', 'end of proof', 'black', 'square']},
    {char: '«', html: '&#171;', unicode: 'U+00AB', tags: ['guillemet gauche', 'left-pointing double angle quotation mark', 'ponctuation']},
    {char: '»', html: '&#187;', unicode: 'U+00BB', tags: ['guillemet droit', 'right-pointing double angle quotation mark', 'ponctuation']},
    {char: '‹', html: '&#8249;', unicode: 'U+2039', tags: ['guillemet simple vers la gauche', 'single left-pointing angle quotation mark', 'ponctuation']},
    {char: '›', html: '&#8250;', unicode: 'U+203A', tags: ['guillemet simple vers la droite', 'single right-pointing angle quotation mark', 'ponctuation']},
    {char: '‸', html: '&#8248;', unicode: 'U+2038', tags: ['chevron d\'insertion', 'caret', 'ponctuation']},
    {char: '∞', html: '&#8734;', unicode: 'U+221E', tags: ['infini', 'infinity', 'symbol', 'sign']},
    {char: '⊶', html: '&#8886;', unicode: 'U+22B6', tags: ['original de', 'original of']},
    {char: '⊷', html: '&#8887;', unicode: 'U+22B7', tags: ['image de', 'image of']},
    {char: '⊸', html: '&#8888;', unicode: 'U+22B8', tags: ['multijection', 'multimap']},
    {char: '⊹', html: '&#8889;', unicode: 'U+22B9', tags: ['matrice hermitienne conjuguée', 'hermitian conjugate matrix']},
    {char: '⌂', html: '&#8962;', unicode: 'U+2302', tags: ['maison', 'house', 'symbol', 'icon']},
    {char: '⌕', html: '&#8981;', unicode: 'U+2315', tags: ['enregistreur téléphonique', 'relephone recorder']},
    {char: '⌗', html: '&#8983;', unicode: 'U+2317', tags: ['carré de visualisation', 'viewdata square']},
    {char: '⌘', html: '&#8984;', unicode: 'U+2318', tags: ['symbole de point d\'intérêt', 'place of interest sign']},
    {char: '⌚', html: '&#8986;', unicode: 'U+231A', tags: ['montre', 'watch', 'icon', 'symbol']},
    {char: '⌛', html: '&#8987;', unicode: 'U+231B', tags: ['sablier', 'hourglass', 'icon', 'symbol']},
    {char: '⌨', html: '&#9000;', unicode: 'U+2328', tags: ['clavier', 'keyboard', 'icon', 'symbol']},
    {char: '⎈', html: '&#9096;', unicode: 'U+2388', tags: ['symbole roue de bateau', 'helm symbol']},
    {char: '⎗', html: '&#9111;', unicode: 'U+2397', tags: ['page précédente', 'previous page']},
    {char: '⎘', html: '&#9112;', unicode: 'U+2398', tags: ['page suivante', 'next page']},
    {char: '⎙', html: '&#9113;', unicode: 'U+2399', tags: ['symbole imprimer écran', 'print screen symbol']},
    {char: '⎚', html: '&#9114;', unicode: 'U+239A', tags: ['symbole nettoyer écran', 'clear screen symbol']},
    {char: '⏎', html: '&#9166;', unicode: 'U+23CE', tags: ['symbole retour de chariot', 'return symbol']},
    {char: '⏏', html: '&#9167;', unicode: 'U+23CF', tags: ['symbole éjection', 'eject symbol', 'icon']},
    // symbols between U+23E9 and U+23FA (audio player & time icons)
    // symbols between U+2460 and U+24FF (circled numbers & letters)
    {char: '◸', html: '&#9720;', unicode: 'U+25F8', tags: []},
    {char: '◹', html: '&#9721;', unicode: 'U+25F9', tags: []},
    {char: '◺', html: '&#9722;', unicode: 'U+25FA', tags: []},
    {char: '◿', html: '&#9727;', unicode: 'U+25FF', tags: []},
    {char: '☀', html: '&#9728;', unicode: 'U+2600', tags: []},
    {char: '☁', html: '&#9729;', unicode: 'U+2601', tags: []},
    {char: '☂', html: '&#9730;', unicode: 'U+2602', tags: []},
    {char: '☔', html: '&#9748;', unicode: 'U+2614', tags: []},
    {char: '☎', html: '&#9742;', unicode: 'U+260E', tags: []},
    {char: '☏', html: '&#9743;', unicode: 'U+260F', tags: []},
    {char: '☕', html: '&#9749;', unicode: 'U+2615', tags: []},
    {char: '☘', html: '&#9752;', unicode: 'U+2618', tags: []},
    {char: '☠', html: '&#9760;', unicode: 'U+2620', tags: []},
    {char: '☢', html: '&#9762;', unicode: 'U+2622', tags: []},
    {char: '☣', html: '&#9763;', unicode: 'U+2623', tags: []},
    {char: '☼', html: '&#9788;', unicode: 'U+263C', tags: []},
    {char: '☽', html: '&#9789;', unicode: 'U+263D', tags: []},
    {char: '☾', html: '&#9790;', unicode: 'U+263E', tags: []},
    {char: '♀', html: '&#9792;', unicode: 'U+2640', tags: []},
    {char: '♂', html: '&#9794;', unicode: 'U+2642', tags: []},
    {char: '⚛', html: '&#9883;', unicode: 'U+269B', tags: []},
    {char: '⚐', html: '&#9872;', unicode: 'U+2690', tags: []},
    {char: '⚑', html: '&#9873;', unicode: 'U+2691', tags: []},
    {char: '⚠', html: '&#9888;', unicode: 'U+26A0', tags: []},
    {char: '✁', html: '&#9985;', unicode: 'U+2701', tags: []},
    {char: '✂', html: '&#9986;', unicode: 'U+2702', tags: []},
    {char: '✃', html: '&#9987;', unicode: 'U+2703', tags: []},
    {char: '✆', html: '&#9990;', unicode: 'U+2706', tags: []},
    {char: '❍', html: '&#10061;', unicode: 'U+274D', tags: []},
    {char: '❏', html: '&#10063;', unicode: 'U+274F', tags: []},
    {char: '❐', html: '&#10064;', unicode: 'U+2750', tags: []},
    {char: '❑', html: '&#10065;', unicode: 'U+2751', tags: []},
    {char: '❒', html: '&#10066;', unicode: 'U+2752', tags: []},
    {char: '⟁', html: '&#10177;', unicode: 'U+27C1', tags: []},
    // emoticon
    {char: '☹', html: '&#9785;', unicode: 'U+2639', tags: []},
    {char: '☺', html: '&#9786;', unicode: 'U+263A', tags: []},
    {char: '☻', html: '&#9787;', unicode: 'U+263B', tags: []},
    {char: '😀', html: '&#128512;', unicode: 'U+1F600', tags: []},
    {char: '😁', html: '&#128513;', unicode: 'U+1F601', tags: []},
    {char: '😂', html: '&#128514;', unicode: 'U+1F602', tags: []},
    {char: '😃', html: '&#128515;', unicode: 'U+1F603', tags: []},
    {char: '😄', html: '&#128516;', unicode: 'U+1F604', tags: []},
    {char: '😅', html: '&#128517;', unicode: 'U+1F605', tags: []},
    {char: '😆', html: '&#128518;', unicode: 'U+1F606', tags: []},
    {char: '😇', html: '&#128519;', unicode: 'U+1F607', tags: []},
    {char: '😈', html: '&#128520;', unicode: 'U+1F608', tags: []},
    {char: '😉', html: '&#128521;', unicode: 'U+1F609', tags: []},
    {char: '😊', html: '&#128522;', unicode: 'U+1F60A', tags: []},
    {char: '😋', html: '&#128523;', unicode: 'U+1F60B', tags: []},
    {char: '😌', html: '&#128524;', unicode: 'U+1F60C', tags: []},
    {char: '😍', html: '&#128525;', unicode: 'U+1F60D', tags: []},
    {char: '😎', html: '&#128526;', unicode: 'U+1F60E', tags: []},
    {char: '😏', html: '&#128527;', unicode: 'U+1F60F', tags: []},
    {char: '😐', html: '&#128528;', unicode: 'U+1F610', tags: []},
    {char: '😑', html: '&#128529;', unicode: 'U+1F611', tags: []},
    {char: '😒', html: '&#128530;', unicode: 'U+1F612', tags: []},
    {char: '😓', html: '&#128531;', unicode: 'U+1F613', tags: []},
    {char: '😔', html: '&#128532;', unicode: 'U+1F614', tags: []},
    {char: '😕', html: '&#128533;', unicode: 'U+1F615', tags: []},
    {char: '😖', html: '&#128534;', unicode: 'U+1F616', tags: []},
    {char: '😗', html: '&#128535;', unicode: 'U+1F617', tags: []},
    {char: '😘', html: '&#128536;', unicode: 'U+1F618', tags: []},
    {char: '😙', html: '&#128537;', unicode: 'U+1F619', tags: []},
    {char: '😚', html: '&#128538;', unicode: 'U+1F61A', tags: []},
    {char: '😛', html: '&#128539;', unicode: 'U+1F61B', tags: []},
    {char: '😜', html: '&#128540;', unicode: 'U+1F61C', tags: []},
    {char: '😝', html: '&#128541;', unicode: 'U+1F61D', tags: []},
    {char: '😞', html: '&#128542;', unicode: 'U+1F61E', tags: []},
    {char: '😟', html: '&#128543;', unicode: 'U+1F61F', tags: []},
    {char: '😠', html: '&#128544;', unicode: 'U+1F620', tags: []},
    {char: '😡', html: '&#128545;', unicode: 'U+1F621', tags: []},
    {char: '😢', html: '&#128546;', unicode: 'U+1F622', tags: []},
    {char: '😣', html: '&#128547;', unicode: 'U+1F623', tags: []},
    {char: '😥', html: '&#128549;', unicode: 'U+1F625', tags: []},
    {char: '😦', html: '&#128550;', unicode: 'U+1F626', tags: []},
    {char: '😧', html: '&#128551;', unicode: 'U+1F627', tags: []},
    {char: '😨', html: '&#128552;', unicode: 'U+1F628', tags: []},
    {char: '😩', html: '&#128553;', unicode: 'U+1F629', tags: []},
    {char: '😪', html: '&#128554;', unicode: 'U+1F62A', tags: []},
    {char: '😫', html: '&#128555;', unicode: 'U+1F62B', tags: []},
    {char: '😭', html: '&#128557;', unicode: 'U+1F62D', tags: []},
    {char: '😮', html: '&#128558;', unicode: 'U+1F62E', tags: []},
    {char: '😯', html: '&#128559;', unicode: 'U+1F62F', tags: []},
    {char: '😰', html: '&#128560;', unicode: 'U+1F630', tags: []},
    {char: '😱', html: '&#128561;', unicode: 'U+1F631', tags: []},
    {char: '😲', html: '&#128562;', unicode: 'U+1F632', tags: []},
    {char: '😳', html: '&#128563;', unicode: 'U+1F633', tags: []},
    {char: '😴', html: '&#128564;', unicode: 'U+1F634', tags: []},
    {char: '😵', html: '&#128565;', unicode: 'U+1F635', tags: []},
    {char: '😶', html: '&#128566;', unicode: 'U+1F636', tags: []},
    {char: '😷', html: '&#128567;', unicode: 'U+1F637', tags: []},
    {char: '😸', html: '&#128568;', unicode: 'U+1F638', tags: []},
    {char: '😹', html: '&#128569;', unicode: 'U+1F639', tags: []},
    {char: '😺', html: '&#128570;', unicode: 'U+1F63A', tags: []},
    {char: '😻', html: '&#128571;', unicode: 'U+1F63B', tags: []},
    {char: '😼', html: '&#128572;', unicode: 'U+1F63C', tags: []},
    {char: '😽', html: '&#128573;', unicode: 'U+1F63D', tags: []},
    {char: '😾', html: '&#128574;', unicode: 'U+1F63E', tags: []},
    {char: '😿', html: '&#128575;', unicode: 'U+1F63F', tags: []},
    {char: '🙀', html: '&#128576;', unicode: 'U+1F640', tags: []}
  ];
  var service = {
    all: all
  };

  return service;
});
